apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp-devops

spec:
  selector:
    app: myapp-devops
  type: LoadBalancer

  ports:
    - port: 8085
      targetPort: 8080
      nodePort: 31202