apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment

spec:
  selector:
    matchLabels:
      app: myapp-devops
  replicas: 2

  template:
    metadata:
      labels:
        app: myapp-devops
    spec:
      containers:
        - name: myapp-devops
          image: ptemghare/myapp:docker_tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8080