---
- name: Kubernetes deploy for myapp
  hosts: minikube_host
  user: minikube

  tasks:
  - name: Deploy for myapp
    command: kubectl apply -f /home/minikube/myapp/myapp-deployment.yml

  - name: Service for my app
    command: kubectl apply -f /home/minikube/myapp/myapp-service.yml