---
- name: Kubernetes deploy for myapp
  hosts: minikube_host
  user: minikube

  tasks:
  - name: Deploy for myapp
    command: kubectl apply -f minikube_deployment/myapp-deployment.yml
    args:
      chdir: "{{ workspace_dir }}"

  - name: Service for my app
    command: kubectl apply -f minikube_deployment/myapp-service.yml
    args:
      chdir: "{{ workspace_dir }}"    